export const translateName = {
  algeria: 'الجزائر',
  bahrain: 'البحرين',
  comoros: 'جزر القمر',
  djibouti: 'جيبوتي',
  egypt: 'مصر',
  iraq: 'العراق',
  jordan: 'الأردن',
  kuwait: 'الكويت',
  lebanon: 'لبنان',
  libya: 'ليبيا',
  mauritania: 'موريتانيا',
  morocco: 'المغرب',
  oman: 'عمان',
  palestine: 'فلسطين',
  qatar: 'قطر',
  'saudi-arabia': 'السعودية',
  somalia: 'الصومال',
  sudan: 'السودان',
  syria: 'سوريا',
  tunisia: 'تونس',
  'united-arab-emirates': 'الإمارات',
  yemen: 'اليمن'
};
